name: Deploy Backend

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/fullstack-dashboard/backend
            git fetch
            git checkout testing
            git pull origin testing
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart backend
